### PR TITLE
Resolve #247

### LINKED ISSUE #247: Certain ConfigContexts cause NullPointerExceptions despite having documented defaults
**TL;DR: we aren't handling some configuration parameters in the execution path which have documented default values**

Despite the defaults listed in [README.md](README.md#configuration), certain implementations of `ConfigContext` result in `NullPointerException`s. Adding getters for `disableNativeSignatures` and `noAuth` to these classes would save some trouble for developers that choose to use these classes. One option is to implement getters in these classes if the behavior of null is best decided by the class itself. Most of these classes use `MantaUtils.parseBooleanOrNull`

~Problematic Classes~ Classes that do what they say they do:
 - `MapConfigContext`: uses `MantaUtils.parseBooleanOrNull` which returns null when passed null
 - `EnvVarConfigContext`: uses `MantaUtils.parseBooleanOrNull` as well
 - `StandardConfigContext`: doesn't implement anything, which is probably as intended and implies the null-handling for default behavior belongs outside these classes
 - ~`ChainedConfigContext`~: abstracts over arrays of multiple `ConfigContext`s and probably shouldn't be concerned with this kind of thing

Alternatively, we could modify the lines that cause the `NullPointerException`s codepath to check handle nulls explicitly, specifically the following two lines
 - https://github.com/joyent/java-manta/blob/master/java-manta-client/src/main/java/com/joyent/manta/client/MantaClient.java#L207
 - https://github.com/joyent/java-manta/blob/master/java-manta-client/src/main/java/com/joyent/manta/http/MantaConnectionFactory.java#L171 Interestingly enough line 165 in that same file does explicit null checking for `useNativeCodeToSign`

Code used to verify which classes throw and which don't:

https://gist.github.com/tjcelaya/df63bfe932afff07de4f501d6daff241

### PR DESCRIPTION
**Pull request by tjcelaya**
Handle potentially-NPE-inducing configuration params that have documented defaults

See #247

### CODE REVIEW

File: java-manta-client/src/main/java/com/joyent/manta/client/MantaClient.java [hunk 1]
```diff
@@ -205,7 +206,7 @@ public MantaClient(final ConfigContext config) {
         final KeyPair keyPair = keyPairFactory.createKeyPair();
 
         final Signer.Builder builder = new Signer.Builder(keyPair);
-        if (config.disableNativeSignatures()) {
+        if (ObjectUtils.firstNonNull(config.disableNativeSignatures(), false)) {
```
Comment (dekobon) [inline java-manta-client/src/main/java/com/joyent/manta/client/MantaClient.java]: I suggest that you add a constant field to `DefaultsConfigContext`, so that you reference the default value rather than explicitly set it here.

File: java-manta-client/src/main/java/com/joyent/manta/http/MantaConnectionFactory.java [hunk 2]
```diff
@@ -160,15 +160,10 @@ public MantaConnectionFactory(final ConfigContext config,
...
-        final boolean useNativeCodeToSign;
-
-        useNativeCodeToSign = config.disableNativeSignatures() == null
-                || !config.disableNativeSignatures();
-
         final HttpSignatureAuthScheme authScheme;
 
         // If we have auth disabled, then we don't assign any signer classes
-        if (config.noAuth()) {
+        if (ObjectUtils.firstNonNull(config.noAuth(), false)) {
```
Comment (dekobon) [inline java-manta-client/src/main/java/com/joyent/manta/http/MantaConnectionFactory.java]: Same comment as above.

File: java-manta-client/src/main/java/com/joyent/manta/config/BaseChainedConfigContext.java [hunk 3]
```diff
@@ -312,7 +312,7 @@ public String getEncryptionPrivateKeyPath() {
     public void overwriteWithContext(final ConfigContext context) {
         /* If a default context is being used to overwrite after this
          * context has been initialized, then we want to be careful to not
-         * overwrite values that have already been set with defaults. */
+         * overwrite values that have already been set by non-default contexts. */
         boolean isDefaultContext = context instanceof DefaultsConfigContext;
```
Comment (dekobon) [inline java-manta-client/src/main/java/com/joyent/manta/config/BaseChainedConfigContext.java]: Do we want this logic to apply for all subclasses of DefaultConfigContext? I don't know what would be right or wrong, but that would be the inflection point to decide between .equals() and instanceof.

Comment (tjcelaya) [inline java-manta-client/src/main/java/com/joyent/manta/config/BaseChainedConfigContext.java]: While it's unlikely that someone would extend `DefaultsConfigContext` we could make that class `final`. We'd lose the ability to mock that class using plain Mockito but it would enforce the expectation that defaults are only coming from one place.

Comment (dekobon) [inline java-manta-client/src/main/java/com/joyent/manta/config/BaseChainedConfigContext.java]: Or you could just check equality with .class.equals()

**Comment by tjcelaya** [comment]
@dekobon Created constants instead of using `BaseConfigContext.DEFAULT_CONFIG.foo()`

Although I did switch to `.getClass().equals()` for the statement you were asking about I want to leave `DefaultsConfigContext` as `final` since I don't think we should allow consumers to extend it.

**Comment by dekobon** [comment]
I almost always error on the side of never declaring classes final because as an integrator, I've had to do so much black magic in the past because the author of a library couldn't foresee that someone might want to extend a class.

**Comment by tjcelaya** [comment]
I guess I could envision a really weird situation where someone might need to inject configuration through the `DefaultsConfigContext` class, changed back.
