### PR TITLE
AES-CTR Returning Incorrect Byte Range (#207)

### LINKED ISSUE #207: AES-CTR Returning Incorrect Byte Range
The aes-ctr plaintext range translation to ciphertext range is returning incorrect values.  Additionally, validation checks have a couple off by one errors.

The impact is that clients doing random requests on large files may download more data than necessary, or potentially request non-existent data.  The off by one errors are less likely to be run into, but could possibly result in bugs in client's software, transitively.

### PR DESCRIPTION
**Pull request by uxcn**
Fixes #207.

Exposes bug with MACs (MantaEncryptedObjectInputStreamTest).

### CODE REVIEW

File: java-manta-client/src/main/java/com/joyent/manta/client/crypto/AesCtrCipherDetails.java [hunk 1]
```diff
@@ -64,60 +64,57 @@ public boolean plaintextSizeCalculationIsAnEstimate() {
...
 
-        // How many bytes do we offset in the first block
-        long plaintextStartAdjustment = startInclusive % blockSize;
+        // How many bytes do we offset in the first block?
+        final long plaintextBytesToSkipInitially = startInclusive % blockSize;
 
-        // The first block is considered block 0
-        double startBlockNumber = Math.floor(startInclusive / blockSize);
+        // Get the ciphertext block index for the start byte (zero based)
+        final long startingBlockNumberInclusive = startInclusive / blockSize;
```
Comment (dekobon) [inline java-manta-client/src/main/java/com/joyent/manta/client/crypto/AesCtrCipherDetails.java]: This makes sense. Math.floor() is unneeded for integer division.

File: java-manta-client/src/main/java/com/joyent/manta/client/crypto/AesCtrCipherDetails.java [hunk 2]
```diff
@@ -64,60 +64,57 @@ public boolean plaintextSizeCalculationIsAnEstimate() {
...
 
-        // Content-Range: bytes=adjustedStart-adjustedEnd
-        adjustedStart = ((long) startBlockNumber) * blockSize;
+        // Get the ciphertext byte position for the start block (block size bytes per block)
+        final long ciphertextStartPositionInclusive = startingBlockNumberInclusive * blockSize;
 
-        // Get the full block for the end range, plus an additional block
-        double endBlockNumber = Math.ceil(endInclusive / blockSize) + 1;
+        // Get the ciphertext block index for the end byte (zero based)
+        final long endingBlockNumberInclusive = endInclusive / blockSize;
```
Comment (dekobon) [inline java-manta-client/src/main/java/com/joyent/manta/client/crypto/AesCtrCipherDetails.java]: Mail.ceil() is unneeded. Why don't we want to read an additional block? I realize that we are doing AES/CTR/NoPadding, but if I recall correctly, there is no way to know if you are at the end of a block and finished or continuing onto the next block.

File: java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java [hunk 3]
```diff
@@ -176,15 +176,15 @@ protected void canRandomlyReadPlaintextPositionFromCiphertext(final SecretKey se
                 decryptor.init(Cipher.DECRYPT_MODE, secretKey, cipherDetails.getEncryptionParameterSpec(iv));
                 long adjustedPlaintextRange = cipherDetails.updateCipherToPosition(decryptor, startPlaintextRange);
 
-                byte[] adjustedCipherText = Arrays.copyOfRange(ciphertext, (int) startCipherTextRange, (int) endCipherTextRange);
+                byte[] adjustedCipherText = Arrays.copyOfRange(ciphertext, (int) startCipherTextRange, (int) Math.min(ciphertext.length, endCipherTextRange + 1));
                 byte[] out = decryptor.doFinal(adjustedCipherText);
                 byte[] decrypted = Arrays.copyOfRange(out, (int) adjustedPlaintextRange,
```
Comment (dekobon) [inline java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java]: By having to use the Math.min() function here, that means that our return value from `ranges.getCiphertextEndPositionInclusive()` is incorrect. When doing HTTP range requests, we may not know the actual size of the ciphertext before doing the request.

File: java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java [hunk 4]
```diff
@@ -176,15 +176,15 @@ protected void canRandomlyReadPlaintextPositionFromCiphertext(final SecretKey se
...
-                        (int) adjustedPlaintextLength + (int) adjustedPlaintextRange);
+                        (int) Math.min(out.length, adjustedPlaintextLength));
```
Comment (dekobon) [inline java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java]: By having to use the Math.min() function here, that means that our return value from `ranges.getCiphertextEndPositionInclusive()` is incorrect. When doing HTTP range requests, we may not know the actual size of the ciphertext before doing the request.

File: java-manta-client/src/main/java/com/joyent/manta/client/crypto/AesCtrCipherDetails.java (hunk 2 above)
Comment (dekobon) [inline java-manta-client/src/main/java/com/joyent/manta/client/crypto/AesCtrCipherDetails.java]: I designed the MantaEncryptedObjectInputStream to bound on the amount of plaintext bytes read in order to deal with any problems calculating ciphertext positions of ranges. For some algorithms and modes, we can never get the exact byte to end on. I'm trying to understand where above the off by one error is. Can you point this out?

Comment (uxcn) [inline java-manta-client/src/main/java/com/joyent/manta/client/crypto/AesCtrCipherDetails.java]: With AES-CTR, ciphertext bytes directly line up with plaintext bytes.  Another way to describe is that the number of blocks is *always*...

    (end_block - start_block) + 1

AES-CTR isn't padded, so the last block in the range may not be an entire block if the range spans to the last block.  So you can't know the exact number of ciphertext bytes without knowing the size of the object.  But, per Range Request RFC (7233), requesting a larger range than exists is *not* an error as long as it begins in some existing range (only the existing range will be returned).

So, the number of bytes to request from manta in an AES-CTR range *can* always be...

    blocks * blocksize

or

    ((end_block - start_block) + 1) * blocksize

And, ciphertext start and end are...

     start_block * blocksize
     ((end_block + 1) * blocksize) - 1

And, length of plaintext with skip bytes is...

    request_end - (start_block * blocksize)

If you use these equations, you get the results I updated in `AesCtrCipherDetailsTest#translateByteRangeReturnsCorrectRange`.

The equations might not generalize to all ciphers, but AES-CTR is the only cipher effectively using it since `AesCtrCipherDetails` is the only implementation with the specific calculation (it's not implemented in `AbstractAesCipherDetails`).  Obviously these exclude any MAC.

These errors weren't off by one, the calculations were just incorrect.  Off by one had to do with comparing a zero based index to a byte count for maximum plaintext size (`AesCtrCipherDetails#L78`, `AesCtrCipherDetails#L89`).

File: java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java (hunk 4 above)
Comment (uxcn) [inline java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java]: Exactly, since the bytes for all blocks are requested, and AES-CTR isn't padded, more bytes than exist may be requested using the above calculations.  There's no way to know this without knowing content length (HTTP request).

The content length (HTTP request) isn't necessary for this though.  Per Range Request RFC (7233) it is *not* an error to request more bytes than exist, and only the existing bytes are returned (which is emulated using `Math.min`).

**Comment by geek** [comment]
@uxcn there is a test failure in travis: `MantaEncryptedObjectInputStreamTest.canReadByteRangeStarting25bytesFromEndToEndAesCtr128`

https://travis-ci.org/joyent/java-manta/jobs/202723437

**Comment by uxcn** [comment]
@geek I actually noticed the test was failing before I submitted the PR.  @dekobon asked me to submit the PR anyway.

As best as I can tell, `MantaEncryptedObjectInputStream` is subtracting MAC bytes from streams with no MAC, although I haven't been able to resolve this in entirety as of yet.

**Comment by geek** [comment]
@uxcn the test is passing in the 3.0 branch: https://travis-ci.org/joyent/java-manta/jobs/203612053

**Comment by uxcn** [comment]
@geek The changes to range calculation tightened the bounds on the ciphertext ranges that are returned, which I think gave ciphertext ranges requested from manta a *fuzz* factor.  I'm still reading through all the code for `MantaEncryptedObjectInputStream` and dependent classes like `BoundedInputStream`.

**Comment by uxcn** [comment]
@geek This was a bug in `MantaEncryptedObjectInputStreamTest#canReadBytes`.  I'm updating the branch, but it seems there are other test failures.

**Comment by uxcn** [comment]
Here is the exception from the test:

    (com.joyent.manta.client.MantaClientRangeIT)  Time elapsed: 0.064 sec  <<< FAILURE!
    java.lang.IllegalArgumentException: End position must be less than maximum plaintext size (endInclusive=9223372036854775791, plaintextMax=9223372036854775791)
            at com.joyent.manta.client.crypto.AesCtrCipherDetails.translateByteRange(AesCtrCipherDetails.java:92)
            at com.joyent.manta.http.EncryptionHttpHelper.calculateSkipBytesAndPlaintextLength(EncryptionHttpHelper.java:415)
            at com.joyent.manta.http.EncryptionHttpHelper.httpRequestAsInputStream(EncryptionHttpHelper.java:267)
            at com.joyent.manta.client.MantaClient.getAsInputStream(MantaClient.java:408)
            at com.joyent.manta.client.MantaClientRangeIT.canGetWithUnboundedEndRange(MantaClientRangeIT.java:119)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
            at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
            at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
            at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
            at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
            at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
            at org.testng.TestRunner.privateRun(TestRunner.java:782)
            at org.testng.TestRunner.run(TestRunner.java:632)
            at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
            at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
            at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
            at org.testng.SuiteRunner.run(SuiteRunner.java:268)
            at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
            at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
            at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
            at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
            at org.testng.TestNG.run(TestNG.java:1064)
            at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
            at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
            at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
            at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
            at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
            at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

File: java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java [hunk 5]
```diff
@@ -103,21 +103,21 @@ public void translateByteRangeThrowsWithoutEndInclusive() {
...
         Assert.assertEquals(byteRange2.getPlaintextBytesToSkipInitially(), 5);
-        Assert.assertEquals(byteRange2.getLengthOfPlaintextIncludingSkipBytes(), 18);
+        Assert.assertEquals(byteRange2.getLengthOfPlaintextIncludingSkipBytes(), 23);
 
         ByteRangeConversion byteRange3 = AesCtrCipherDetails.INSTANCE_128_BIT.translateByteRange(32, 35);
         Assert.assertEquals(byteRange3.getCiphertextStartPositionInclusive(), 32);
-        Assert.assertEquals(byteRange3.getCiphertextEndPositionInclusive(), 49);
+        Assert.assertEquals(byteRange3.getCiphertextEndPositionInclusive(), 47);
         Assert.assertEquals(byteRange3.getPlaintextBytesToSkipInitially(), 0);
-        Assert.assertEquals(byteRange3.getLengthOfPlaintextIncludingSkipBytes(), 4);
```
Comment (geek) [inline java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java]: Why delete this line?

File: java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java [hunk 6]
```diff
@@ -176,15 +176,15 @@ protected void canRandomlyReadPlaintextPositionFromCiphertext(final SecretKey se
...
                 byte[] out = decryptor.doFinal(adjustedCipherText);
                 byte[] decrypted = Arrays.copyOfRange(out, (int) adjustedPlaintextRange,
-                        (int) adjustedPlaintextLength + (int) adjustedPlaintextRange);
+                        (int) Math.min(out.length, adjustedPlaintextLength));
 
                 String decryptedText = new String(decrypted);
                 String adjustedText = new String(adjustedPlaintext);
 
-                Assert.assertEquals(decryptedText, adjustedText,
+                Assert.assertEquals(adjustedText, decryptedText,
```
Comment (geek) [inline java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java]: actual should come first... this is reversed

**Comment by geek** [comment]
@uxcn looks good!

Have you executed the byte range integration tests with these changes? (make sure to add the `usingEncryption=true` parameter)

File: java-manta-client/src/main/java/com/joyent/manta/client/crypto/AesCtrCipherDetails.java (hunk 1 above)
Comment (dekobon) [inline java-manta-client/src/main/java/com/joyent/manta/client/crypto/AesCtrCipherDetails.java]: Alternatively, do we want to be using Math.floorDiv()?

File: java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java (hunk 5 above)
Comment (uxcn) [inline java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java]: This is an error; is it better to edit the commit or fix in new commit?

Comment (geek) [inline java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java]: either way, whatever is easier.

File: java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java (hunk 6 above)
Comment (uxcn) [inline java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java]: The `adjustedText` is the actual one; the `decryptedText` runs through the range request and decryption.

**Comment by uxcn** [comment]
@geek I ran the integration suite and did run into some problems (java-manta-it).  I haven't manually set `usingEncryption` so far.  The github CI looks okay, but I am still digging through some issues in the integration tests.

**Comment by uxcn** [comment]
@geek I tracked down the issue in the integration tests to the off by one issue fixed in `AesCtrCipherDetails#translateByteRange`.  `EncryptionHttpHelper` is translating implicit ranges into explicit ranges (i.e. `Long.MAX_VALUE` to indicate an unbounded end).  This also potentially incurs an extra http request to manta.

File: java-manta-client/src/main/java/com/joyent/manta/http/EncryptionHttpHelper.java [hunk 7]
```diff
@@ -411,9 +411,18 @@ public MantaObjectInputStream httpRequestAsInputStream(final HttpUriRequest requ
             binaryEndPositionInclusive = ciphertextSize;
         // This is the typical case like: bytes=3-44
         } else {
+
+            long scaledPlaintextEnd = plaintextEnd;
+
+            // interpret maximum plaintext value as unbounded end
+            if (plaintextEnd == cipherDetails.getMaximumPlaintextSizeInBytes()) {
+
```
Comment (geek) [inline java-manta-client/src/main/java/com/joyent/manta/http/EncryptionHttpHelper.java]: extra newline

File: java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java [hunk 8]
```diff
@@ -103,21 +103,22 @@ public void translateByteRangeThrowsWithoutEndInclusive() {
...
-        Assert.assertEquals(byteRange2.getLengthOfPlaintextIncludingSkipBytes(), 18);
+        Assert.assertEquals(byteRange2.getLengthOfPlaintextIncludingSkipBytes(), 23);
 
         ByteRangeConversion byteRange3 = AesCtrCipherDetails.INSTANCE_128_BIT.translateByteRange(32, 35);
         Assert.assertEquals(byteRange3.getCiphertextStartPositionInclusive(), 32);
-        Assert.assertEquals(byteRange3.getCiphertextEndPositionInclusive(), 49);
+        Assert.assertEquals(byteRange3.getCiphertextEndPositionInclusive(), 47);
         Assert.assertEquals(byteRange3.getPlaintextBytesToSkipInitially(), 0);
         Assert.assertEquals(byteRange3.getLengthOfPlaintextIncludingSkipBytes(), 4);
+
```
Comment (geek) [inline java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java]: extra newline

**Comment by geek** [comment]
LGTM... great work!

File: java-manta-client/src/main/java/com/joyent/manta/http/EncryptionHttpHelper.java (hunk 7 above)
Comment (uxcn) [inline java-manta-client/src/main/java/com/joyent/manta/http/EncryptionHttpHelper.java]: I usually leave no space if there aren't brackets, and space if there are brackets (my thoughts were that visually it's easier to notice the distinct code block reading the code).  I'm definitely not set on a specific style though.

File: java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java (hunk 8 above)
Comment (uxcn) [inline java-manta-client/src/test/java/com/joyent/manta/client/crypto/AesCtrCipherDetailsTest.java]: Oops.
