### PR TITLE
Fixing Issue#480

### LINKED ISSUE #480: Integration tests should be structured better to support accounts that have SnapLinks disabled
When running just MantaClientIT, the following tests fail due to snaplinks being disabled:
```
MantaClientIT.canMoveDirectoryWithContents
MantaClientIT.canMoveFileToDifferentPrecreatedDirectory
MantaClientIT.canMoveFileToDifferentUncreatedDirectoryCreationEnabled
MantaClientIT.testHead
MantaClientIT.testPutJsonLink
MantaClientIT.testPutLink
```

We should probably have a separate integration test class that does only operations related to snaplinks and remove all tests that use snaplinks from MantaClientIT.

### PR DESCRIPTION
**Pull request by nairashwin952013**
This Integration should close #480.

### CODE REVIEW

File: java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java [hunk 1]
```diff
@@ -0,0 +1,198 @@
...
+
+    private static final String TEST_DATA = "Arise,Awake And Do Not Stop Until Your Goal Is Reached.";
+
+    private MantaClient mantaClient;
+
+    private String testPathPrefix;
+
+    @BeforeClass
+    @Parameters({"usingEncryption"})
+    public void beforeClass(@Optional Boolean usingEncryption) throws IOException {
```
Comment (dekobon) [inline java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java]: Perhaps attempt to create a snaplink in the before method. If it fails with the message that snaplinks aren't supported, then we should throw a `SkipException` to indicate that the whole test class can't be run. This approach may have a problem, if so - I think the alternative is to throw the `SkipException` in each individual test.

Comment (nairashwin952013) [reply java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java]: Noted.

Comment (nairashwin952013) [reply java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java]: I am opting for the latter since I agree with you when you posited: *It will be relatively safer from the design perspective*. I have changed occurrences of ```putSnapLink()``` in the there tests that it was implemented in and didn't make any changes to the others, would you like me to include them in all ?

Comment (nairashwin952013) [reply java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java]: A final change will also be added to the class description which will state the conditions under which this ```integration-test``` will be skipped.

Comment (nairashwin952013) [reply java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java]: New changes passed in ```staging```.

File: java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java [hunk 2]
```diff
@@ -0,0 +1,225 @@
...
+        mantaClient.putDirectory(testPathPrefix, true);
+    }
+
+    @AfterClass
+    public void afterClass() throws IOException {
+        IntegrationTestConfigContext.cleanupTestDirectory(mantaClient, testPathPrefix);
+    }
+
+    @Test
+    public final void canMoveDirectoryWithContents() throws IOException {
```
Comment (dekobon) [inline java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java]: You can omit the `@Test` annotation if you have specified it at the class level.

File: java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java [hunk 3]
```diff
@@ -0,0 +1,225 @@
+/*
```
Comment (dekobon) [inline java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java]: The following tests still fail when snaplinks are disabled:

```
MantaClientSnapLinksIT.canMoveDirectoryWithContents
MantaClientSnapLinksIT.canMoveFileToDifferentPrecreatedDirectory
MantaClientSnapLinksIT.canMoveFileToDifferentUncreatedDirectoryCreationEnabled
```

They are not properly skipped.

Comment (nairashwin952013) [reply java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java]: Is there like a flag to check whether snaplinks are disabled for an account ?

File: java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java [hunk 4]
```diff
@@ -0,0 +1,219 @@
...
+
+        boolean sourceIsDeleted = !mantaClient.existsAndIsAccessible(source);
+        Assert.assertTrue(sourceIsDeleted, "Source directory didn't get deleted: "
+                + source);
+    }
+
+    private void skipSnapLinkTest(final String linkPath, final String objectPath) throws IOException, MantaClientHttpResponseException {
+        try {
+            mantaClient.putSnapLink( linkPath, objectPath, null);
+        } catch (MantaClientHttpResponseException e) {
```
Comment (nairashwin952013) [inline java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java]:
```
catch (MantaClientHttpResponseException e) {
          if (e.getServerCode().equals(SNAPLINKS_DISABLED_ERROR)) {
                final String message =
                        "This integration-test class can't be run since SnapLinks" +
                                "have been disabled for this account";
                LOG.warn(message);
                throw new SkipException(message, e);
            }
         throw e;
    }
```

File: java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java (hunk 3 above)
Comment (nairashwin952013) [reply java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSnapLinksIT.java]: Noted.

**Comment by nairashwin952013** [comment]
Addressed all feedback provided, #496 is eligible to be merged into the ```release-branch```.

**Comment by nairashwin952013** [comment]
Carol notified for her feedback.

**Comment by nairashwin952013** [comment]
This Pull-Request has been squashed and merged onto the ```release-branch```.
