### PR TITLE
Fix #297

### LINKED ISSUE #297: 503 response on smaller-than-minimum-sized MPU part (or during complete) causes IOException
Running `EncryptedServerSideMultipartManagerIT#canRetryUploadPart` with Charles Web Proxy rewriting response code of the final part triggers the exception attached below. Unfortunately `EncryptionStateRecorder` does not provide a straightforward way to handle this situation so this fix will be more complicated. Snapshots might need to include streams instead of just the `Cipher` and `HMac` objects:

```
java.io.IOException: write(-103) failed: stream is closed

	at org.apache.commons.io.output.ClosedOutputStream.write(ClosedOutputStream.java:48)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.OutputStream.write(OutputStream.java:75)
	at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:72)
	at org.bouncycastle.jcajce.io.CipherOutputStream.write(Unknown Source)
	at com.joyent.manta.util.HmacOutputStream.write(HmacOutputStream.java:74)
	at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:90)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2147)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
	at com.joyent.manta.client.crypto.EncryptingPartEntity.writeTo(EncryptingPartEntity.java:134)
	at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:121)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:160)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.joyent.manta.client.multipart.ServerSideMultipartManager.uploadPart(ServerSideMultipartManager.java:330)
	at com.joyent.manta.client.multipart.ServerSideMultipartManager.uploadPart(ServerSideMultipartManager.java:68)
	at com.joyent.manta.client.multipart.EncryptedMultipartManager.uploadPart(EncryptedMultipartManager.java:290)
	at com.joyent.manta.client.multipart.EncryptedMultipartManager.uploadPart(EncryptedMultipartManager.java:46)
	at com.joyent.manta.client.multipart.AbstractMultipartManager.uploadPart(AbstractMultipartManager.java:115)
	at com.joyent.manta.client.multipart.EncryptedServerSideMultipartManagerIT.canRetryUploadPart(EncryptedServerSideMultipartManagerIT.java:521)
```

### PR DESCRIPTION
**Pull request by tjcelaya**
Created a unit test for the situation where EncryptingPartEntity finalizes encryption. Not passing yet.

(issue #297)

### CODE REVIEW

**Comment by tjcelaya** [comment]
Summary of changes:

- Modify `EncryptingEntityHelper#makeCipherOutputForStream` to accept `SupportedCipherDetails` and `Cipher` objects instead of `EncryptionContext` so we can pass in cloned `Cipher`s
- update `makeCipherOutputForStream` callers to comply with the aforementioned change
- copy buffer content into new `MultipartOutputStream`. Cleanup led to the discovery that this part is unnecessary since the buffer is always empty between parts, *can someone validate this?*
- replace the `cipherStream` field of `EncryptionState` completely instead of drilling into private state
- include `boolean lastPartAuthWritten` in `EncryptionStateSnapshot`

**Comment by tjcelaya** [comment]
After reviewing with @dekobon the following changes have been requested:

 - [ ] Extract `wrapped.uploadPart` call with surrounding `EncryptionStateRecorder` usage
 - [ ] follow up with @cburroughs  in a later issue about `MultipartOutputStream`'s buffer

File: java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptionStateSnapshot.java [hunk 1]
```diff
@@ -29,26 +28,42 @@
     private final int lastPartNumber;
 
     /**
-     * Cloned HMAC state, may be null if Cipher provides Authenticated Encryption. See {@link EncryptionStateRecorder}.
+     * EncryptionState's lastPartAuthWritten.
      */
-    private final HMac hmac;
```
Comment (cburroughs) [inline java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptionStateSnapshot.java]: Removed because the HMAC will be within the cloned hmaOutputStream, correct?

File: java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptionStateSnapshot.java [hunk 2]
```diff
@@ -83,8 +106,8 @@ public boolean equals(final Object o) {
         }
 
         final EncryptionStateSnapshot that = (EncryptionStateSnapshot) o;
-        return lastPartNumber == that.lastPartNumber
-                && cipher == that.cipher
-                && hmac == that.hmac;
+        return Objects.equals(uploadId, that.uploadId)
```
Comment (cburroughs) [inline java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptionStateSnapshot.java]: Sorry if I breezed by on the last patch, why does this class needs equals & hashcode methods.

**Comment by cburroughs** [comment]
Sorry for the delay, how the questions help.

File: java-manta-client-kryo-serialization/src/main/java/com/joyent/manta/serialization/EncryptionStateSerializer.java [hunk 3]
```diff
@@ -183,7 +183,7 @@ public EncryptionState read(final Kryo kryo, final Input input, final Class<Encr
         final HMac hmac = kryo.readObjectOrNull(input, HMac.class);
 
         final OutputStream cipherStream = EncryptingEntityHelper.makeCipherOutputForStream(
-                multipartStream, encryptionContext, hmac);
+                multipartStream, encryptionContext.getCipherDetails(), encryptionContext.getCipher(), hmac);
```
Comment (dekobon) [inline java-manta-client-kryo-serialization/src/main/java/com/joyent/manta/serialization/EncryptionStateSerializer.java]: I suggest that the java-manta-client and java-manta-client-kryo-serialization must be the same version. We should probably document this.

File: java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptionStateSnapshot.java (hunk 1 above)
Comment (tjcelaya) [inline java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptionStateSnapshot.java]: Yup

File: java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptedMultipartManager.java [hunk 4]
```diff
@@ -396,6 +389,42 @@ private HttpContext buildRequestContext(final HttpContext context) {
...
+                                                      final HttpEntity entity) throws IOException {
+        final EncryptionStateSnapshot snapshot = EncryptionStateRecorder.record(encryptionState, upload.getId());
+        try {
+            final MantaMultipartUploadPart part =
+                    wrapped.uploadPart(upload.getWrapped(), partNumber, entity, httpContext);
+            encryptionState.setLastPartNumber(partNumber);
+            return part;
+        } catch (Exception e) {
+            if (encryptionState.getLastPartNumber() != partNumber) {
+                // didn't make it to encryptionState.setLastPartNumber(partNumber)
```
Comment (tjcelaya) [inline java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptedMultipartManager.java]: Yup

File: java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptedMultipartManager.java [hunk 5]
```diff
@@ -396,6 +389,42 @@ private HttpContext buildRequestContext(final HttpContext context) {
...
+     * @param upload          multipart upload object
+     * @param partNumber      part number to identify relative location in final file
+     * @param httpContext     additional request context, may be null
+     * @param encryptionState encryption state that should be reset in case of error
+     * @param entity          Apache HTTP Client entity instance
+     * @return the successfully uploaded part
+     * @throws IOException in case of network errors, though MantaMultipartException will be thrown in
+     *                     case of invalid response code
+     */
+    private MantaMultipartUploadPart uploadPartSafely(final EncryptedMultipartUpload<WRAPPED_UPLOAD> upload,
```
Comment (tjcelaya) [inline java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptedMultipartManager.java]: Not sure why that name didn't pop into my head last night, I was too tired. Making this change.

File: java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptedMultipartManager.java [hunk 6]
```diff
@@ -317,17 +307,20 @@ public void complete(final EncryptedMultipartUpload<WRAPPED_UPLOAD> upload,
...
         try {
             Stream<? extends MantaMultipartUploadTuple> finalPartsStream = partsStream;
+
             if (!encryptionState.isLastPartAuthWritten()) {
                 ByteArrayOutputStream remainderStream = encryptionState.remainderAndLastPartAuth();
                 if (remainderStream.size() > 0) {
-                    MantaMultipartUploadPart finalPart = wrapped.uploadPart(upload.getWrapped(),
-                                                                            encryptionState.getLastPartNumber() + 1,
-                                                                            remainderStream.toByteArray());
+                    final MantaMultipartUploadPart finalPart = uploadPartSafely(
```
Comment (tjcelaya) [inline java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptedMultipartManager.java]: Making this change.

File: java-manta-client/src/main/java/com/joyent/manta/client/crypto/EncryptingEntityHelper.java [hunk 7]
```diff
@@ -83,12 +88,15 @@ public static OutputStream makeCipherOutputForStream(
      * wrapped requires changes to EncryptionStateRecorder!
      *
      * @param httpOut output stream for writing to the HTTP network socket
-     * @param encryptionContext current encryption running state
+     * @param cipherDetails current encryption running state's cipher details
+     * @param cipher current encryption running state's cipher
```
Comment (tjcelaya) [inline java-manta-client/src/main/java/com/joyent/manta/client/crypto/EncryptingEntityHelper.java]: I'll clarify this.

File: java-manta-client-kryo-serialization/src/main/java/com/joyent/manta/serialization/EncryptionStateSerializer.java (hunk 3 above)
Comment (tjcelaya) [inline java-manta-client-kryo-serialization/src/main/java/com/joyent/manta/serialization/EncryptionStateSerializer.java]: Added a compatibility method and a note to the installation section in the README

File: java-manta-client/src/main/java/com/joyent/manta/client/crypto/EncryptingEntityHelper.java [hunk 8]
```diff
@@ -83,12 +88,15 @@ public static OutputStream makeCipherOutputForStream(
...
      * @param hmac current HMAC object with the current checksum state
      * @return a new stream configured based on the parameters
      */
     public static OutputStream makeCipherOutputForStream(
-            final OutputStream httpOut, final EncryptionContext encryptionContext,
+            final OutputStream httpOut,
+            final SupportedCipherDetails cipherDetails,
+            final Cipher cipher,
```
Comment (tjcelaya) [inline java-manta-client/src/main/java/com/joyent/manta/client/crypto/EncryptingEntityHelper.java]: Not a blocker for this PR but do we want to validate that the hmac is not null when the `CipherDetails` indicates the cipher is not AEAD?

File: java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptionStateSnapshot.java (hunk 2 above)
Comment (tjcelaya) [inline java-manta-client/src/main/java/com/joyent/manta/client/multipart/EncryptionStateSnapshot.java]: They're not strictly necessary but it was a matter of habit. The fact that `EncryptionState` has those methods was the primary motivation.
