### PR TITLE
Wrap read() and other operations IOExceptions in more detailed MantaIOException instances

### LINKED ISSUE #260: IOException thrown from MantaEncryptedObjectInputStream during read() missing context values
The following exception was reported, but no context was included. It looks like we rethrow caught exceptions without adding any context in

https://github.com/joyent/java-manta/blob/2a591afa0b501e008e69e1a7c762889eeb1ff548/java-manta-client/src/main/java/com/joyent/manta/client/crypto/MantaEncryptedObjectInputStream.java#L472

```
com.joyent.manta.org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 3366879; received: 2243367
        at com.joyent.manta.org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178) ~[validator.jar:?]
        at com.joyent.manta.org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135) ~[validator.jar:?]
        at com.joyent.manta.org.apache.commons.io.input.BoundedInputStream.read(BoundedInputStream.java:123) ~[validator.jar:?]
        at com.joyent.manta.org.apache.commons.io.input.BoundedInputStream.read(BoundedInputStream.java:105) ~[validator.jar:?]
        at org.bouncycastle.jcajce.io.CipherInputStream.nextChunk(Unknown Source) ~[bcprov-jdk15on-156.jar:1.56.0]
        at org.bouncycastle.jcajce.io.CipherInputStream.read(Unknown Source) ~[bcprov-jdk15on-156.jar:1.56.0]
        at java.io.FilterInputStream.read(FilterInputStream.java:107) ~[?:1.8.0_65]
        at com.joyent.manta.client.crypto.MantaEncryptedObjectInputStream.read(MantaEncryptedObjectInputStream.java:465) ~[validator.jar:?]
        at com.joyent.manta.client.crypto.MantaEncryptedObjectInputStream.read(MantaEncryptedObjectInputStream.java:415) ~[validator.jar:?]
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2146) ~[validator.jar:?]
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102) ~[validator.jar:?]
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123) ~[validator.jar:?]
```

It seems straightforward to at the very least replace the bare

```
else {
    throw e;
}
```
with
```
else {
    MantaIOException me = new MantaIOException(e);
    annotateException(me);
    throw me;
}
```

### PR DESCRIPTION
**Pull request by dekobon**
Fixes #260

### CODE REVIEW

File: java-manta-client/src/main/java/com/joyent/manta/client/MantaObjectOutputStream.java [hunk 1]
```diff
@@ -310,7 +310,10 @@ public synchronized void close() throws IOException {
         } catch (InterruptedException e) {
             // continue execution if interrupted
         } catch (ExecutionException e) {
-            throw new MantaIOException(e);
+            MantaIOException mioe = new MantaIOException(e);
```
Comment (cburroughs) [inline java-manta-client/src/main/java/com/joyent/manta/client/MantaObjectOutputStream.java]: Without access to `HttpRequest`/`HttpResponse`, this won't actually have context like the request-id, right?

Comment (dekobon) [inline java-manta-client/src/main/java/com/joyent/manta/client/MantaObjectOutputStream.java]: We can actually get it through the logging MDC threadlocal store. I'll update the PR with the request id added.

File: java-manta-client/src/main/java/com/joyent/manta/client/crypto/MantaEncryptedObjectInputStream.java [hunk 2]
```diff
@@ -731,6 +746,12 @@ private void annotateException(final ExceptionContext exception) {
         exception.setContextValue("authenticationEnabled", this.authenticateCiphertext);
         exception.setContextValue("threadName", Thread.currentThread().getName());
 
+        final String requestId = MDC.get(RequestIdInterceptor.MDC_REQUEST_ID_STRING);
```
Comment (tjcelaya) [inline java-manta-client/src/main/java/com/joyent/manta/client/crypto/MantaEncryptedObjectInputStream.java]: This makes sense for `MantaObjectOutputStream` since there isn't a response directly accessible but it seems more straightforward to use `this.getRequestId()` here unless I'm missing something. All the constructors for `MantaObjectEncryptedInputStream` and `MantaObjectInputStream` seem to have access to a `MantaObjectResponse`

Either `getRequestId()` or `getHeaderAsString(MantaHttpHeaders.REQUEST_ID)` would be preferable I think.

Comment (dekobon) [inline java-manta-client/src/main/java/com/joyent/manta/client/crypto/MantaEncryptedObjectInputStream.java]: Yes! Making the change.
